### ISSUE TITLE
imageResize function working but not giving the proper size as required .

### ISSUE THREAD

**Issue by abhaychauhan** [BuildFire/contactUsPlugin#14]
I have pulled the sdk and this time resize function is working but it is not giving the required sizes of  images .There is difference in size of two images , that are resized through resize function with same dimension.

Below are the links of images that have been resized:

http://s7obnu.cloudimage.io/s/resizenp/400x200/https://imagelibserver.s3.amazonaws.com/fbfc2e49-39d8-11e5-9d04-02f7ca55c361/abaa5de0-3a72-11e5-945e-7d01ee3c1728.jpg

http://s7obnu.cloudimage.io/s/resizenp/400x200/https://imagelibserver.s3.amazonaws.com/fbfc2e49-39d8-11e5-9d04-02f7ca55c361/f60edc80-3a72-11e5-945e-7d01ee3c1728.jpg

**Comment by DanielHindi** [comment]
The service wont distort the image. Both images have two different ratios. If you want the image cropped you can use the crop method or use CSS to compensate
