### ISSUE TITLE
Layout 2

### ISSUE THREAD

**Issue by ianblair44** [BuildFire/contactUsPlugin#21]
Map not showing at the top. Just showing the placeholder.

Carousel not showing up. Just the placeholder. 

<img width="1208" alt="screen shot 2015-09-09 at 10 51 50 am" src="https://cloud.githubusercontent.com/assets/2794086/9769744/d8cf3018-56e0-11e5-941c-befdeacfa4f7.png">

**Comment by sakshityagi** [comment]
This was fixed earlier. Should be working now.
