### ISSUE TITLE
Divider Changes

### ISSUE THREAD

**Issue by ianblair44** [BuildFire/contactUsPlugin#23]
Only show the divider when there is both an Address and Dynamic links. 

When there isn't one or the other, the divider serves no purpose. 

<img width="392" alt="screen shot 2015-09-11 at 11 03 26 am" src="https://cloud.githubusercontent.com/assets/2794086/9822376/eebc44c0-5874-11e5-9562-25dec1416d26.png">

**Comment by sakshityagi** [comment]
@ianblair44 Done. Please review.
