### ISSUE TITLE
BFW001-2  -  Update button in Settings area is truncated

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/contactUsPlugin#26]
Priority: Low
Reproducability: Always
Device / OS / Browser / Version: Windows 7 - Chrome

ACTUAL RESULTS:- 
Update button is not fully shown 

EXPECTED RESULTS: 
Update button should be fully shown to the user 

OTHER NOTES / ERROR MESSAGES:- 

gattestetacc_20@mailinator.com test1234 

Screen resolution - 1366x768 

screenshot: http://bugs8.gatserver.com/uploads/58af109c0efe2f610da8489434a94ed3.png

Steps to reproduce this issue
1. Access Buildfire
2. Go to Plugins > Add Plugin
3. Click Settings
4. Notice the truncated button label

**Comment by NancyHaddad** [comment]
Logged in issue

**Comment by ianblair44** [comment]
@NancyHaddad if this is logged elsewhere can we close this out?
