### ISSUE TITLE
BFW001-6  -  Adding spaces on plugin titles returns a 'page not found' or 404 page

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/contactUsPlugin#27]
Priority: High
Reproducibility: Always
Device / OS / Browser / Version: Windows 7 / Chrome

ACTUAL RESULTS:-
When user adds space/s as title of the plugin, the page returns a 404 page. 

EXPECTED RESULTS: 
Form should not allow users to add spaces as title to avoid error. Or if it's allowed, it should redirect to the correct page. 

OTHER NOTES / ERROR MESSAGES:- 

Email: gattesteracc_04@mailinator.com Pass: test1234 

Video: http://bugs8.gatserver.com/uploads/1bb6758b82f5532efa669fe739d192b3.mp4

Steps to reproduce this issue
1. Access Buildfire
2. Go to Plugins > Add Plugin
3. Click Settings
4. Notice the truncated button label

Steps to reproduce this issue
1. Go to http://int2.myapp.buildfire.com/ and login with valid details.
2. From the left menu, select Plugins > Add Plugin.
3. From the list, select Youtube or Vimeo or Contact Us by clicking on 'add plugin'.
4. You will be asked to add a title for the plugin. Add spaces on the title.
5. Notice that the page redirects to a page not found 404 page. This happens to Youtube or Vimeo or Contact Us plugin.

**Comment by NancyHaddad** [comment]
Logged in Issue

**Comment by ianblair44** [comment]
@NancyHaddad same goes for these other ones.
