### ISSUE TITLE
BFW001-57  -  Contact Us/Plugin - Insert/Edit Image - Removing the image generate console error

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/contactUsPlugin#28]
[Grey Area - Unknown Expected Behaviour]
Priority: Critical
Reproducibility: Often 
Device / OS / Browser / Version: Windows 7 Home Premium / IE 11

ACTUAL RESULTS:- Exploring Insert/Edit Image, user used the link from Dropbox as the Image Source. After image was added user tried removing the image on the Body Content generates a console error 'Object doesn't support this action.' pauses the site by Debugger. 

EXPECTED RESULTS: User is able to remove the inserted image added using the Insert/Edit Image on Body of Content. 

OTHER NOTES / ERROR MESSAGES:- 

username: gattesteracc_16@mailinator.com password: test1234 

Video: 
http://bugs8.gatserver.com/uploads/98376b2cc1d63ed020c9696f08559437.mp4 
Screenshots:
http://bugs8.gatserver.com/uploads/e0699bf80495c1b0495438f83027361e.jpg http://bugs8.gatserver.com/uploads/69b9726e759a62bffd3a8caee31fcad6.jpg

Steps to reproduce this issue
1. Open the site and login credentials
2. On the left side menu, click on Active Plugin
3. Select Edit on Contact Us  created plugin
4. Under Content, go to Body Content, click on Insert option
5. Enter the image source, description etc. then click OK
6. Delete the inserted image on the Body Content box ( Console error 'Object doesn't support this action.' is generated)

**Comment by ianblair44** [comment]
Moved to cs repo
