### ISSUE TITLE
BFW001-38  -  ContactUs - Add Action: Can't select link to Facebook page from add action options

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/contactUsPlugin#30]
Priority: High
Reproducibility: Always
Device / OS / Browser / Version: Windows 8 - Chrome

ACTUAL RESULTS:- Can't select link to Facebook page from add action options 

EXPECTED RESULTS: Should be able to select link to Facebook page option when adding an action. 

OTHER NOTES / ERROR MESSAGES:- Note that all the options can be selected except for link to Facebook page as seen in the video attachment. 

Desktop resolution is 1366x768 

Username: gattesteracc_06@mailinator.com pass:test1234 

Video: http://bugs8.gatserver.com/uploads/5da349e3b7f5923fadb3578ccb828cff.mp4

Steps to reproduce this issue
1. Log in. Add contact us plug in.
2. Add an image to carousel.
3. Beside the selected image click add action button.
4. On the action field drop down arrow select link to Facebook page.
5. Notice that link to Facebook page is not working or can't be selected.

**Comment by NancyHaddad** [comment]
Logged in issue
