### ISSUE TITLE
BFW001-41  -  Test Case - All Plugins - Media Gallery: 'Upload Successful' is shown upon uploading an unsupported image file

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/contactUsPlugin#31]
Priority: High
Reproducibility: Always
Device / OS / Browser / Version: Windows 7 | Mozilla Firefox 40.0.3

ACTUAL RESULTS:-
'Upload Successful' is shown upon uploading an unsupported image file
Broken thumbnail is shown after uploading image

EXPECTED RESULTS:
As per the Media Gallery note, 'Images must be in jpg, jpeg, or png format and under 1MB.', 'Upload successful' should not show when user tries to upload an unsupported image like bmp, tiff etc. There should be an error prompt shown

OTHER NOTES / ERROR MESSAGES:- 

NOTE: This also happens upon uploading an image with more than 1MB in size Screen resolution: 1366 x 788 

Account: gattesteracc_14@mailinator.com / test1234 

Video: http://bugs8.gatserver.com/uploads/a8de42bf8f329e3cf92fe20440011a81.mp4

Steps to reproduce this issue
1. Login to http://int2.myapp.buildfire.com/
2. Click on Plugins in the Control Panel
3. Click on Add Plugin
4. Click on the Contact Us's "Add" button
5. Enter a name and click "Add"
6. Once plugin is added, click icon thumbnail
7. Click 'Import Images' and select any unsupported images (bmp, tiff, etc)
8. Notice that 'Upload Successful' is shown upon uploading an unsupported image file

**Comment by ianblair44** [comment]
Moved to cs repo.
