### ISSUE TITLE
BFW001-37  -  ContactUs - ImageCarousel: Carousel modification doesn't work

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/contactUsPlugin#32]
Priority: High
Reproducibility: Always
Device / OS / Browser / Version: Windows 8 - Chrome

ACTUAL RESULTS:-
Carousel modification doesn't work. 

EXPECTED RESULTS:-
Should work after adding image that would make up a carousel. 

OTHER NOTES / ERROR MESSAGES:- 
Note that all modification apply on the preview layout, but upon making a carousel, it doesn't seem to be working because it doesn't apply to the layout preview unlike any other modification. 

Desktop resolution is 1366x768 Browser resolution is at default 100% 

Console log: http://bugs8.gatserver.com/uploads/530c84f6639f7704d88aef567867463d.log 

Username: gattesteracc_06@mailinator.com pass: test1234 

Video: http://bugs8.gatserver.com/uploads/573fe214801d6533c590547774824fc5.mp4

**Comment by kmtabish** [comment]
We have tested it on http://int2.myapp.buildfire.com/ with Username gattesteracc_06@mailinator.com. its not replicating.

**Comment by sakshityagi** [comment]
Tested again. Working fine. Please review and close the issue.
