### ISSUE TITLE
BFW001-25  -  Chrome/Device: Content does not show up in device and error 404 appears in console.

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/contactUsPlugin#33]
Priority: High
Reproducibility: Often
Device / OS / Browser / Version: Windows 8.1 Chrome Version 45

ACTUAL RESULTS:- It was observed that often after refreshing the page, the content of the plug-ins does not appear in the device on the left. There is persistent loading and console shows error 404. 

EXPECTED RESULTS: Content in the device should appear properly. 

OTHER NOTES / ERROR MESSAGES:- 
User name: gattesteracc_17@mailinator.com Password: test1234 Screen resolution: 1366x768. 

Video: 
http://bugs8.gatserver.com/uploads/12aad3aafd613200707217d88bc06edd.mp4

Steps to reproduce this issue
- Navigate to http://int2.myapp.buildfire.com/#/addPlugin.
- Observe that often the page keeps loading persistently and that the content does not appear in the device.

**Comment by ianblair44** [comment]
Moved to cs repo
