### ISSUE TITLE
BFW001-48  -  Contact us: link inserted using the WYSIWYG editor does not appear in the app's screen

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/contactUsPlugin#34]
Priority: High
Reproducibility: Always
Device / OS / Browser / Version: Windows 10, Chrome

ACTUAL RESULTS:-
Link inserted using the WYSIWYG editor does not appear in the app's screen 

EXPECTED RESULTS:-
Link inserted using the WYSIWYG editor should appear in the app's screen 

OTHER NOTES / ERROR MESSAGES:- 
Username: gattesteracc_11@mailinator.com	password: test1234 Screen resolution: 1600x900 

Screenshot:
http://bugs8.gatserver.com/uploads/695a6d96e8b6ade62eae22e8c991e5fe.jpg 

Update: further test shows that the problem is due to the blue background masking the blue url, see http://bugs8.gatserver.com/uploads/86d4d087918e6f19a8b9bdd2ac7a2821.jpg

Steps to reproduce this issue
1. Open test site
2. Log in with credentials
3. Go to the plugins tab > Add Plugin - > Add Contact us
4. Enter something for the Contact us plugin title
5. In the WYSIWYG editor, click Insert -> Insert/Edit link
6. Enter details in the insert link pop-up window
7. Try to find the link in the app's screen

**Comment by kmtabish** [comment]
Tested several times on http://int2.myapp.buildfire.com/ .Working fine for me.
