### ISSUE TITLE
BFW001-16  -  Insert Selection needs to be clicked 3 - 4 times to close the modal window and goes back to plugin details

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/contactUsPlugin#36]
Priority: High
Reproducibility: Often
Device / OS / Browser / Version: Windows 7 Home Premium / IE 11

ACTUAL RESULTS:-
Trying to Add image, after uploading a photo, clicking on the Insert Selection button is done 3 to 4 times before it closes the modal window and goes back to the Contacts plugin details. 

EXPECTED RESULTS:
After a photo is uploaded clicking on Insert selection button once closes the modal window and goes back to the plugin contacts details. 

OTHER NOTES / ERROR MESSAGES:- 

Username: gattesteracc_16@mailinator.com password: test1234 

Video: http://bugs8.gatserver.com/uploads/a8f1bec29191b552850e6c466ba09b4f.mp4 

Log: http://bugs8.gatserver.com/uploads/41ebeef07eaa1eb4e5372271538d6def.txt

Steps to reproduce this issue
1. Open the link and login credentials
2. Click Plugin
3. Click Add Plugin
4. On Contacts Plugin click Add
5. Enter the title of Contact Plugin and click Add
6. Details of created Contact plugin, click on Add Image
7. Select photo to upload then click Open button
8. Click on the uploaded photo and select Insert selection button ( notice it should be click several times before modal window closes)

**Comment by ianblair44** [comment]
Referenced in other tickets.
