### ISSUE TITLE
BFW001-62 - Contact Plugin/Add Link - Add/Edit Action Modal window opens up again after clicking Save button when the selected Action is Call & Send SMS Message

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/contactUsPlugin#37]
Priority: High
Reproducibility: Always
Device / OS / Browser / Version: Windows 7 Home Premium / IE 11

ACTUAL RESULTS:-
On Add link, after selecting the Call & Send SMS Message is selected as Action and then Save button is clicked, the Add/Edit Action Modal window opens up again although the created link is already saved. 

EXPECTED RESULTS:
Add/Edit Action Modal window only appears once after clicking the Add link button. 

OTHER NOTES / ERROR MESSAGES:- 
Video:
http://bugs8.gatserver.com/uploads/b0d582a62b7a8c09f72a6b7320461b51.mp4 http://bugs8.gatserver.com/uploads/e52b5f3d3bb8689e9f74db72f098cf1b.mp4 

Log:
http://bugs8.gatserver.com/uploads/8ccccfbd8afdc090d8d4b98cd0b23496.txt

Steps to reproduce this issue
1. Open the link and login credentials
2. On the left side, click Plugin
3. Under Plugin, select Active Plugin
4. On the list of plugins, select Edit under Contact Plugin
5. On the Contact plugin, click Add link
6. Enter Title of link, action as Call/Send SMS Message
7. Enter Number then click save button (observe that after clicking the save button, the Add/Edit action window opens up again)

**Comment by ianblair44** [comment]
This could be due to the same issue that is causing duplicate modals to pop up.

**Comment by sakshityagi** [comment]
Yes, This seems fixed now. Please review and close the issue.
