### ISSUE TITLE
BFW001-35  -  [Contact Us] Cannot add a link to a map

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/contactUsPlugin#38]
Priority: Medium
Reproducibility: Often
Device / OS / Browser / Version: Win 7 Ult x64, Chrome and Firefox

ACTUAL RESULTS:-
The map does not load (9/10). 

EXPECTED RESULTS:-
The map should load. 

OTHER NOTES / ERROR MESSAGES:-
Email: gattesteracc_05@mailinator.com / Password: test1234 

Reviewed on following resolutions: 1920x1200 and 1366x768 

The map loaded once or twice, after changing values, adding new locations/names and waiting. 

Video:
http://bugs8.gatserver.com/uploads/33f2d545e98d32db9419228c39840273.mp4 

http://postimg.org/image/yxarljx1n/

Steps to reproduce this issue
- Add a Contact Us plugin
- Proceed to Plugins-> Active Plugins
- Edit the Contact us plugin
- Press the Add Link button
- Change Action to Link to Map
- Observe the issue

**Comment by ianblair44** [comment]
moved to CS repo
