### ISSUE TITLE
BFW001-31  -  [Add Plugin] Pressing plugin name or BuildFire link leads to an empty page

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/contactUsPlugin#40]
Priority: Medium
Reproducibility: Always
Device / OS / Browser / Version: Win 7 Ult x64, Chrome and Firefox

ACTUAL RESULTS:-
Inside Add Plugin section, if one of the three plugin names is pressed it will redirect to an empty page. The same issue occurs when the BuildFire link is pressed. 

EXPECTED RESULTS:-
The user should be redirected to a plausible page. 

OTHER NOTES / ERROR MESSAGES:-
email: gattesteracc_05@mailinator.com / password: test1234 

Reviewed on following resolutions: 1920x1200 and 1366x768 

BuildFire link is situated in Plugins->Add Plugin-> each plugin has a part "Developed by" and the BuildFire link. 

Video:
http://bugs8.gatserver.com/uploads/50517166bb23c20fc0fcff1432235feb.mp4 

http://postimg.org/image/c6oqujqkx/

Steps to reproduce this issue
- Proceed to Plugins-> Add Plugin
- Press on any of the three names (Contact Us/Vimeo/youtubePlugin) and BuildFire link
- Observe that user is redirected to an empty page

**Comment by ianblair44** [comment]
moved.
