### ISSUE TITLE
BFW001-54  -  Media Gallery: Can able to upload image more than 1MB

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/contactUsPlugin#41]
Priority: Medium
Reproducibility: Always
Device / OS / Browser / Version: Windows 7 Chrome v. 44.0.2403.157 m

ACTUAL RESULTS:-
Can able to upload image that have a size more than 1MB under Media Gallery. 

EXPECTED RESULTS:-
User should not able to add image that was more than 1mb size. 

OTHER NOTES / ERROR MESSAGES:- 

email: gattesteracc_09@mailinator.com password: test1234 

Video: http://bugs8.gatserver.com/uploads/7bebaa815d6f019dde47db5c0f8cc7f9.mp4

Steps to reproduce this issue
1. Log into BuildFire http://int2.myapp.buildfire.com
2. Log in with your assigned credentials
3. Click Plugins.
4. Click Add Plugin.
5. Click Add Image.
6. Upload jpeg file with more than 1MB file size.

**Comment by ianblair44** [comment]
Moved to CS repo
