### ISSUE TITLE
BFW001-15  -  Chrome: "Help" button doesn't redirect to a Help page.

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/contactUsPlugin#42]
Priority: Medium
Reproducibility: Always
Device / OS / Browser / Version: Windows 8.1 Chrome Version 45

ACTUAL RESULTS:-
"Help" button doesn't redirect to a Help page. 

EXPECTED RESULTS:-
It is expected that user is redirected to a page where they can get help advice. 

OTHER NOTES / ERROR MESSAGES:- 
Username: gattesteracc_17@mailinator.com Password: test1234 Screen resolution: 1366x768. 

Please find attached a video of the issue: 
http://bugs8.gatserver.com/uploads/7b6900643ecf7471fb8c84fba1cc3015.mp4

Steps to reproduce this issue
- Navigate to http://int2.myapp.buildfire.com/#/addPlugin.
- Click the "Help" button.
- Observe you are not redirected to a page where you can get help.

**Comment by NancyHaddad** [comment]
Help button not implemented yet
