### ISSUE TITLE
BFW001-27  -  ContactUs - Edit - Design: Preview layout doesn't follow the design of the layout selected

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/contactUsPlugin#43]
Priority: Medium
Reproducibility: Always
Device / OS / Browser / Version: Windows 8 - Chrome

ACTUAL RESULTS:- 
Preview layout doesn't follow the design of the layout selected 

EXPECTED RESULTS: 
Should follow the design of the selected layout. 

OTHER NOTES / ERROR MESSAGES:- 
In this scenario the selected layout is layout number 1, where in it has an display image at the top the map, note that on the design layout the address is not displayed on the banner image hence it is displayed on the area below the map, but on the app preview layout the address is displayed on the top of the map or in the banner image instead on the are below the map. 

username: gattesteracc_06@mailinator.com pass:test1234 

Video: http://bugs8.gatserver.com/uploads/863edf61d35d376447a6a2082110b2b7.mp4 

Desktop resolution is 1366x768 (recommended) browser resolution is at default 100%

Steps to reproduce this issue
- Log in.
- Add contact us plug in and edit.
- Enter image background, address
- Go to design tab.
- Select layout 1.
- look at the preview.
- Notice that the preview layout doesn't follow the layout 1 or the selected layout. Note that it doesn't happen in the layout 2, layout 2 is properly followed or copied.

**Comment by kmtabish** [comment]
This is because there are no carousel images. That's why the contact and address info moves up.
