### ISSUE TITLE
BFW001-22  -  Contact Plugin - Added Image cannot be removed. Delete X button is not working

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/contactUsPlugin#44]
Priority: Medium
Reproducibility: Often
Device / OS / Browser / Version: Windows 7 Home Premium / IE 11

ACTUAL RESULTS:-
After the image is added, user is unable to remove it. The delete x button is not working 

EXPECTED RESULTS:
User can delete/remove the added image. 

OTHER NOTES / ERROR MESSAGES:- 

username: gattesteracc_16@mailinator.com password: test1234 

Log: http://bugs8.gatserver.com/uploads/3da552dc497bb4a34de8eb26aefff67a.txt 

Video: http://bugs8.gatserver.com/uploads/e3280c03efe0819eec5af4213ef5d04c.mp4

Steps to reproduce this issue
1. Open the link and login credentials
2. Click on Plugin
3. Click on Active Plugin
4. All created plugin are listed, click on Edit to select the Contact Us plugin
5. Under Image Carousel, click on the x button on the photo uploaded to remove it (notice the button is not working the image is not deleted)

**Comment by kmtabish** [comment]
After clicking on x button, you need to click on save button in the bottom of popup to save changes. Also there is an issue with image carousel popup that if you do not select "Action" the popup does not show the options below it, not even cancel and save.

**Comment by ianblair44** [comment]
@kmtabish make sure the pop up shows up in a place where the user can see it then.

**Comment by sakshityagi** [comment]
@ianblair44 Setting popup's position is not configurable by us. We just call buildfire api. I think this can be handled by buildfire.
