### ISSUE TITLE
 BFW001-34  -  Contact Us: Cancel and Save button bar appears twice in Add/Edit Action page

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/contactUsPlugin#45]
Priority: Medium
Reproducibility: Always
Device / OS / Browser / Version: Win 7 Ult x64, Chrome and Firefox

ACTUAL RESULTS:- 
After switching Action to Call Number, the Cancel/Save button bar will appear twice if any other action is selected. 

EXPECTED RESULTS:-
There should be only one button bar. 

OTHER NOTES / ERROR MESSAGES:- 

email: gattesteracc_05@mailinator.com / password: test1234 

Reviewed on following resolutions: 1920x1200 and 1366x768 

Video:
http://bugs8.gatserver.com/uploads/7774d14479059ff21e71dc7df0804e99.mp4

Steps to reproduce this issue
1. Add a Contact Us plugin
2. Proceed to Plugins-> Active Plugins
3. Edit the Contact Us plugin
4. Locate Add Link button and press it
5. Switch Action to Call Number
6. Switch to any other Action
7. Observe issue

**Comment by ianblair44** [comment]
moved
