### ISSUE TITLE
BFW001-30  -  Plug-in Instances: Although all plug-ins have been deleted, the plug-in instances still appear.

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/contactUsPlugin#46]
Priority: Medium
Reproducibility: Always
Device / OS / Browser / Version: Windows 8.1 Chrome Version 45

ACTUAL RESULTS:-
Although all plug-ins have been deleted, the plug-in instances still appear. 

EXPECTED RESULTS:-
The plug-in instances should disappear when the respective plug-ins are deleted. 

OTHER NOTES / ERROR MESSAGES:- 
Username: gattesteracc_17@mailinator.com Password: test1234 Screen resolution: 1366x768. 

Video:
http://bugs8.gatserver.com/uploads/eb1a0f3ac90d75c7e4582d445658c2c9.mp4

Steps to reproduce this issue
- Navigate to http://int2.myapp.buildfire.com/#/addPlugin.
- Click "Plugins" at the left menu
- Click Add Plugin
- Go through the process of creating a plugin 
- Click "Plugins" at the left menu
- Click Side Menu
- Click "Add Plugin Instance" and add the plugin you created before
- Go to Active Plugins and delete the plugin you created
- Go back to Side Menu and observe that the plugin instance still appears

**Comment by NancyHaddad** [comment]
Logged in issue: duplicated in customerservice tickets
