### ISSUE TITLE
BFW001-13  -  All plug-ins/Media Gallery: "Load More" button only loads more images if a new image is uploaded

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/contactUsPlugin#47]
Priority: Medium
Reproducibility: Always
Device / OS / Browser / Version: Windows 8.1 Chrome Version 45

ACTUAL RESULTS:-
"Load More" button only loads more images if a new image is uploaded. Even if there are more images that can be loaded, clicking the button will not load more images. 

EXPECTED RESULTS:-
Clicking the "Load More" button should load more images. 

OTHER NOTES / ERROR MESSAGES:- 

Username: gattesteracc_17@mailinator.com Password: test1234 

Screen resolution: 1366x768. 

Video:
http://bugs8.gatserver.com/uploads/ad7e5a10bcefdfc9134fb4e81a20791f.mp4

Steps to reproduce this issue
1. Navigate to http://int2.myapp.buildfire.com/#/addPlugin.
2. Click the "Add" button next to Contact Us plug-in
3. Click "Add image"
4. Upload many images 
5. Close the window and open it again
6. Click "Load More" and observe no more images are loaded
7. Upload one more image 
8. Click "Load More" and observe that now more images are loaded

**Comment by ianblair44** [comment]
moved
