### ISSUE TITLE
BFW001-14  -  ContactUs - Edit: Body content data is displaying in the address title area and not in the body content area

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/contactUsPlugin#48]
Priority: Medium
Reproducibility: Always
Device / OS / Browser / Version: Windows 8 - Chrome

ACTUAL RESULTS:-
Body content data is displaying in the address title area and not in the body content area. 

EXPECTED RESULTS:-
Should be displayed in the body and not in the address title area. 

OTHER NOTES / ERROR MESSAGES:- 

Resolution: 1366 x 768 

username: gattesteracc_06@mailinator.com pass:test1234 

Video:
http://bugs8.gatserver.com/uploads/41c2e162dad7190b42405cd9f3a04fdb.mp4

Steps to reproduce this issue
1. Log in.
2. Add contact us plug in.
3. Edit contact us plug in.
4. Enter a content on the body.
5. Notice that the content on the body is displaying in the address title area and not in the body.

**Comment by sakshityagi** [comment]
I think, you have not chosen "Display map" option in control panel. Thats why map is not there and the body content moves up like it should. Also the background image will show on full widget screen after updating the plugin. You can check now.

**Comment by sakshityagi** [comment]
Please close the issue if fixed.
