### ISSUE TITLE
BFW001-9  -  Edit button has no functionality when the plugin's name contains special characters

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/contactUsPlugin#49]
Priority: Medium
Reproducibility: Always
Device / OS / Browser / Version: Windows 8 - IE 11

ACTUAL RESULTS:- The edit button for the plugins has no functionality, when the plugin's name contains special characters i.e.: "plugin#1 Co" 

EXPECTED RESULTS: The edit button should work. 

OTHER NOTES / ERROR MESSAGES:- 
email: gattesteracc_03@mailinator.com password: test1234 

Resolution: 1920x1080 

Video:
http://bugs8.gatserver.com/uploads/605277bc8abcba92059ccdd35b12c6de.mp4

Steps to reproduce this issue
1. Go to http://int2.myapp.buildfire.com/ and login
2. From the left menu, select Plugins > Active Plugins.
3. Tap on Edit button on Contact us plugin and observe that an error message appears

**Comment by ianblair44** [comment]
moved
