### ISSUE TITLE
BFW001-33  -  [ContactUs]Edit: Address is disappeared on the preview layout when entering a title address.

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/contactUsPlugin#50]
Priority: Medium
Reproducibility: Always
Device / OS / Browser / Version: Windows 8 - Chrome

ACTUAL RESULTS:-
Address is disappeared on the preview layout when entering a title address. 

EXPECTED RESULTS:-
Address should not disappeared and should be displayed together with the title address. 

OTHER NOTES / ERROR MESSAGES:-
Desktop resolution is at 1366x768 (recommended) Browser resolution is at default 100% 

username: gattesteracc_06@mailinator.com pass: test1234 

Video:
http://bugs8.gatserver.com/uploads/2f0f2a91800f72160c237ab7ad793b7f.mp4 

Log:
http://bugs8.gatserver.com/uploads/50b20de6ea2c018dc7d3a28676797feb.log 

Steps to reproduce this issue
- Log in.
- Add contact us plug in and edit.
- Enter and address and look at the preview.
- Now enter a title address and look at the preview.
- Notice that the address disappeared when adding a title address.

**Comment by ianblair44** [comment]
This is not a bug. This is like this by design. 

DO NOT FIX THIS.
