### ISSUE TITLE
BFW001-44  -  Contact us: No error message when image not selected when inserting image

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/contactUsPlugin#51]
Priority: Low
Reproducibility: Always
Device / OS / Browser / Version: Windows 10 - Chrome

ACTUAL RESULTS:-
When trying to insert an image for the contact us icon, there is no error message when image to be inserted is not selected. 

EXPECTED RESULTS:-
If no image is selected, there should be an error message and the insert image window should not close after clicking Insert Selection. 

OTHER NOTES / ERROR MESSAGES:- 

Username: gattesteracc_11@mailinator.com	password: test1234 

Screen resolution: 1600x900 

Video:
http://bugs8.gatserver.com/uploads/46ea23bb4ce973d447010d973362a5fe.mp4 
Screenshot:
http://bugs8.gatserver.com/uploads/80d69633bc6ec1836eb668e2ae4b13dc.jpg

Steps to reproduce this issue
1. Open test site
2. Log in with credentials
3. Go to the plugins tab > Add Plugin - > Add Contact us
4. Enter something for the Contact us plugin title
5. Click on the icon image to open the Media Gallery window
6. Click "import new files" and upload an image
7. Click Insert Selection

**Comment by ianblair44** [comment]
moved.
