### ISSUE TITLE
BFW001-47  -  Contact Us: Insert pop-up window in WYSIWYG editor requires too much scrolling

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/contactUsPlugin#54]
Priority: Usability
Reproducibility: Always
Device / OS / Browser / Version: Windows 10 - Chrome

ACTUAL RESULTS:-
The Insert pop-up window in WYSIWYG editor is very long and appears outside of the user's view and need one to scroll at least one page before the pop-up fields are visible. 

EXPECTED RESULTS:-
The Insert pop-up window in the WYSIWYG editor should be visible without scrolling. 

OTHER NOTES / ERROR MESSAGES:- 
Username: gattesteracc_11@mailinator.com	password: test1234 

Screen resolution: 1600x900 

Screenshot:
http://bugs8.gatserver.com/uploads/c678727bb1a9ea6ab8383fe338f76b26.jpg

Steps to reproduce this issue
1. Open test site
2. Log in with credentials
3. Go to the plugins tab > Add Plugin - > Add Contact us
4. Enter something for the Contact us plugin title
5. In the WYSIWYG editor, click Insert -> Insert/Edit Image
6. Scroll one page down to see the fields in the pop-up window

**Comment by ianblair44** [comment]
Moved to CS Repo
