### ISSUE TITLE
BFW001-43  -  All Plugins - Background Image: Current image is removed when user click 'x' button on media gallery popup window

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/contactUsPlugin#55]
Priority: High
Reproducibility: Always
Device / OS / Browser / Version: Windows 7 | Mozilla Firefox 40.0.3

ACTUAL RESULTS:- 
Current image is removed when user click 'x' button on media gallery popup window 

EXPECTED RESULTS: 
'x' button should close the window and current selected image should not be deleted, since user does not change anything on his/her current setup 

OTHER NOTES / ERROR MESSAGES:- 

Screen resolution: 1366 x 788 

Browser: Mozilla Firefox 40.0.3 

Account: gattesteracc_14@mailinator.com / test1234 

http://bugs8.gatserver.com/uploads/56f28b61685387eba689fd708b401106.mp4

Steps to reproduce this issue
1. Login to http://int2.myapp.buildfire.com/
2. Add any plugins
3. Click 'Design' tab 
4. Click 'Item List Background Image' 
5. Select image and click Insert Selection
6. After adding take note of the uploaded image
7. Click again the 'Item List Background Image' 
8. Click 'x' button of media gallery popup window
9. Notice that current image is removed when user click 'x' button on media gallery popup window

**Comment by kmtabish** [comment]
should be working now. Please try .

**Comment by sakshityagi** [comment]
Please close the issue if fixed.
