### ISSUE TITLE
BFW001-45  -  Contact us - Links added via "Add link" does not appear anywhere in the app

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/contactUsPlugin#56]
Priority: Low
Reproducibility: Always
Device / OS / Browser / Version: Windows 10, Chrome

ACTUAL RESULTS:
Links added via "Add link" does not appear anywhere in the app. 

EXPECTED RESULTS: 
The link added should appear somewhere in the app's screen. 

OTHER NOTES / ERROR MESSAGES:- 

Username: gattesteracc_11@mailinator.com	
password: test1234 

Screen resolution: 1600x900 

http://bugs8.gatserver.com/uploads/bd3ab57be95f0d0ba2b891d91f4c795e.jpg

Steps to reproduce this issue
1. Open test site
2. Log in with credentials
3. Go to the plugins tab > Add Plugin - > Add Contact us
4. Enter something for the Contact us plugin title
5. Click the Add link button and complete the required field
6. Try to locate the added link in the app's screen

**Comment by kmtabish** [comment]
Updated the plugin. should be working now. please try again.

**Comment by sakshityagi** [comment]
Please close the issue if fixed.
