### ISSUE TITLE
CP CONTACT US - Wysiwyg select image popup issue

### ISSUE THREAD

**Issue by nathankeating** [BuildFire/contactUsPlugin#58]
When you click to add an image to the wysiwyg, the dialogue box appears way down and off the page.

Also, when the popup is up, the background overlay should be white, not black.

**Comment by sakshityagi** [comment]
@ianblair44 This issue is with WYSIWYG, It will be addressed by BuildFire.

**Comment by nathankeating** [comment]
Moved to https://github.com/BuildFire/customerServiceTickets/issues/741
