### ISSUE TITLE
CONTACT US APP / EMULATOR - Address is not clickable

### ISSUE THREAD

**Issue by nathankeating** [BuildFire/contactUsPlugin#59]
Address is not clickable in the app and emulator

**Comment by sakshityagi** [comment]
@ianblair44 On click of address do we have to open some pop up? Can you please provide screen shot for that?

**Comment by ianblair44** [comment]
See the functionality in the old platform. We will keep it the same as that.

**Comment by kmtabish** [comment]
@ianblair44 from where i can check the old functionality?

**Comment by sakshityagi** [comment]
You mean opening maps on the mobile device, when clicked on address?

**Comment by nathankeating** [comment]
When the user clicks the address, it should take them to their native maps application and give them the pin of where the location is. From there, they can get directions.

**Comment by sakshityagi** [comment]
Done. Please review. Working fine on iphone. Need to implement for android as well.
