### ISSUE TITLE
CONTACT US APP / EMULATOR - Layout 1 issues

### ISSUE THREAD

**Issue by nathankeating** [BuildFire/contactUsPlugin#61]
The following issues are occurring in layout 1:

- Dots on carousel not centered
- Dividing lines not at 25% opacity

**Comment by sakshityagi** [comment]
Carousel dots issue is fixed now.

**Comment by sakshityagi** [comment]
@jdm135 Please look into second issue.

**Comment by jdm135** [comment]
@nathankeating Let's keep theme at the very end. I'll be doing a UI check/clean up to finalize these plugins and then we can go over the little theme/design issues then.

**Comment by nathankeating** [comment]
@jdm135 Sounds good
