### ISSUE TITLE
Libraries included in Buildfire SDK

### ISSUE THREAD

**Issue by abhaychauhan** [BuildFire/contactUsPlugin#8]
While implementing carousel, Bootstrap scripts included in SDK of Buildfire are not working but when i include Bootstrap library from Bootstrap site (<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
) it WORKS. 

The same problem occurs during implementation of modal dialog box for showing the form which accepts URL for linking images.

**Comment by DanielHindi** [comment]
Only the CSS file is automatically included. Did you try to add in
bootstrap_UI.js located locally ?
