### ISSUE TITLE
Store Image

### ISSUE THREAD

**Issue by abhaychauhan** [BuildFire/contactUsPlugin#9]
How to save  image in a datastore ? I looked into the Wiki of Buildfire but was unable to find solution the problem.

**Comment by DanielHindi** [comment]
https://github.com/BuildFire/sdk/wiki/How-to-use-ImageLib

This link  explains the image library. All you need to do is open the image
lib dialog
buildfire.imageLib.showDialog(options, callback);
It will give the user a list of previously uploaded images as well as the
opportunity to upload new images. You then receive an array of urls in the
call back
